### ISSUE TITLE
Add continuous integration for text reading pipeline

### ISSUE THREAD

**Issue by adarshp** [ml4ai/skema#21]
We have continuous integration/testing set up for the Rust components of the SKEMA repository, but we should set it up for the text reading pipeline as well.

@kwalcock : @vincentraymond-ua has just added support (https://github.com/ml4ai/skema/pull/20) for continuous integration for this repo that is running on on of our lab servers. Do you think you could work with him to get continuous integration set up for the text reading pipeline as well?

**Comment by kwalcock** [comment]
See #23 at the end.  It's just a guess and may not work.  If the process is begun each time with a new image, there will be a repeated multi-gigabyte download of library dependencies.  If it works at all, the next step would be to cache these dependencies.  In a pinch, that could be achieved with a custom image, which would hopefully be cached itself.

**Comment by adarshp** [comment]
@kwalcock  - looks like there are a few errors. You can view them at http://ci.kraken.sista.arizona.edu/ml4ai/skema (let me and @vincentraymond-ua know if you have trouble accessing the site).

```
[error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
161s
13	[error] http://artifactory.cs.arizona.edu:8081/artifactory/sbt-release/org/clulab/model-streamed-trigram-ser_2.12/1.0.0/model-streamed-trigram-ser_2.12-1.0.0.jar: wrong checksum: /root/.cache/coursier/v1/http/artifactory.cs.arizona.edu%3A8081/artifactory/sbt-release/org/clulab/model-streamed-trigram-ser_2.12/1.0.0/model-streamed-trigram-ser_2.12-1.0.0.jar (expected SHA-1 d3cfa151e5debeb4bcaec5648588d299f36dc8bb in /root/.cache/coursier/v1/http/artifactory.cs.arizona.edu%3A8081/artifactory/sbt-release/org/clulab/model-streamed-trigram-ser_2.12/1.0.0/.model-streamed-trigram-ser_2.12-1.0.0.jar__sha1, got fc61bed3cb9ed4286c96109ae9baa532c560e8a8)
161s
14	[error] 
161s
15	[error] 	at lmcoursier.internal.shaded.coursier.Artifacts$.$anonfun$fetchArtifacts$9(Artifacts.scala:365)
161s
16	[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
161s
17	[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
161s
18	[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.wrap(Task.scala:82)
161s
19	[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
161s
20	[error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
161s
21	[error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
161s
22	[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
161s
23	[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
161s
24	[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
161s
25	[error] 	at java.lang.Thread.run(Thread.java:750)
161s
26	[error] Caused by: lmcoursier.internal.shaded.coursier.cache.ArtifactError$WrongChecksum: wrong checksum: /root/.cache/coursier/v1/http/artifactory.cs.arizona.edu%3A8081/artifactory/sbt-release/org/clulab/model-streamed-trigram-ser_2.12/1.0.0/model-streamed-trigram-ser_2.12-1.0.0.jar (expected SHA-1 d3cfa151e5debeb4bcaec5648588d299f36dc8bb in /root/.cache/coursier/v1/http/artifactory.cs.arizona.edu%3A8081/artifactory/sbt-release/org/clulab/model-streamed-trigram-ser_2.12/1.0.0/.model-streamed-trigram-ser_2.12-1.0.0.jar__sha1, got fc61bed3cb9ed4286c96109ae9baa532c560e8a8)
161s
27	[error] 	at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$validateChecksum$4(FileCache.scala:142)
161s
28	[error] 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
161s
29	[error] 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
161s
30	[error] 	at scala.util.Success.map(Try.scala:213)
161s
31	[error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
161s
32	[error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
161s
33	[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
161s
34	[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
161s
35	[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
161s
36	[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
161s
37	[error] 	at java.lang.Thread.run(Thread.java:750)
161s
38	[error] (grounding / update) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
161s
39	[error] http://artifactory.cs.arizona.edu:8081/artifactory/sbt-release/org/clulab/model-streamed-trigram-ser_2.12/1.0.0/model-streamed-trigram-ser_2.12-1.0.0.jar: wrong checksum: /root/.cache/coursier/v1/http/artifactory.cs.arizona.edu%3A8081/artifactory/sbt-release/org/clulab/model-streamed-trigram-ser_2.12/1.0.0/model-streamed-trigram-ser_2.12-1.0.0.jar (expected SHA-1 d3cfa151e5debeb4bcaec5648588d299f36dc8bb in /root/.cache/coursier/v1/http/artifactory.cs.arizona.edu%3A8081/artifactory/sbt-release/org/clulab/model-streamed-trigram-ser_2.12/1.0.0/.model-streamed-trigram-ser_2.12-1.0.0.jar__sha1, got fc61bed3cb9ed4286c96109ae9baa532c560e8a8)
161s
40	[error] Total time: 139 s (02:19), completed Nov 7, 2022 1:05:14 AM
```

**Comment by adarshp** [comment]
@kwalcock  - just kidding, it seems to be progressing fine: http://ci.kraken.sista.arizona.edu/ml4ai/skema/13/2/2

**Comment by adarshp** [comment]
@kwalcock  - I think the custom image will get cached. If not, I think there may be some Drone plugins that can do this (at least from a quick Google search).

**Comment by kwalcock** [comment]
Thanks for trying it out.  The drone thing looks nifty.  It ran out of memory, so I'll increase that temporarily.  It's using two different large vector files.  Later that can probably be reduced to one.

**Comment by enoriega** [comment]
Can we consider this done? @kwalcock @adarshp

**Comment by adarshp** [comment]
@enoriega - yep, I'll close the issue.
