### ISSUE TITLE
[Text Reading] DyNet fails to run on ARM64 when run with an ARM64 compatible JRE

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/skema#450]
Even if the text reading webapp is built using a base image compatible with ARM64 (ex. [`eclipse-temurin:8-jre-focal`](https://hub.docker.com/_/eclipse-temurin/tags?page=1&name=8-jre-focal)), DyNet fails to load:

```text
[dynet] Checking /skema/text_reading for libdynet_swig.so...
[dynet] Checking /root for libdynet_swig.so...
[dynet] Extracting resource libdynet_swig.so to /tmp/libdynet_swig-2406090845481594232.so...
java.lang.RuntimeException: DyNet could not be loaded!
	at edu.cmu.dynet.internal.dynet_swigJNI.<clinit>(dynet_swigJNI.java:95)
	at edu.cmu.dynet.internal.DynetParams.<init>(DynetParams.java:87)
	at edu.cmu.dynet.Initialize$.initialize(Initialize.scala:14)
	at org.clulab.fatdynet.utils.Initializer$.$anonfun$initialize$1(Initializer.scala:41)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at org.clulab.fatdynet.utils.DebugSynchronizer.during(Synchronizer.scala:52)
	at org.clulab.fatdynet.utils.DebugSynchronizer.doSynchronized(Synchronizer.scala:96)
	at org.clulab.fatdynet.utils.DebugSynchronizer.withoutComputationGraph(Synchronizer.scala:122)
	at org.clulab.fatdynet.utils.Synchronizer$.withoutComputationGraph(Synchronizer.scala:181)
	at org.clulab.fatdynet.utils.Initializer$.initialize(Initializer.scala:37)
	at org.clulab.dynet.Utils$.initializeDyNet(Utils.scala:60)
	at org.clulab.processors.clu.CluProcessor$.<init>(CluProcessor.scala:918)
	at org.clulab.processors.clu.CluProcessor$.<clinit>(CluProcessor.scala)
	at org.clulab.processors.shallownlp.ShallowNLPProcessor.mkDocument(ShallowNLPProcessor.scala:97)
	at org.ml4ai.skema.text_reading.OdinEngine.annotate(OdinEngine.scala:138)
	at org.ml4ai.skema.text_reading.TextReadingPipeline$.newOdinEngine(TextReadingPipeline.scala:140)
	at controllers.HomeController.<init>(HomeController.scala:42)
	at controllers.HomeController$$FastClassByGuice$$4f2e2472.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1094)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131)
	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:436)
	at play.api.inject.ContextClassLoaderInjector.$anonfun$instanceOf$3(Injector.scala:120)
	at play.api.inject.ContextClassLoaderInjector.withContext(Injector.scala:128)
	at play.api.inject.ContextClassLoaderInjector.instanceOf(Injector.scala:120)
	at play.api.inject.RoutesProvider.$anonfun$get$2(BuiltinModule.scala:121)
	at scala.Option.fold(Option.scala:251)
	at play.api.inject.RoutesProvider.get$lzycompute(BuiltinModule.scala:121)
	at play.api.inject.RoutesProvider.get(BuiltinModule.scala:116)
	at play.api.inject.RoutesProvider.get(BuiltinModule.scala:110)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:85)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:77)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:59)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1094)
	at play.api.http.DefaultHttpRequestHandler.routeRequest(HttpRequestHandler.scala:289)
	at play.api.http.JavaCompatibleHttpRequestHandler.routeRequest(HttpRequestHandler.scala:396)
	at play.api.http.DefaultHttpRequestHandler.routeWithFallback$1(HttpRequestHandler.scala:187)
	at play.api.http.DefaultHttpRequestHandler.handlerForRequest(HttpRequestHandler.scala:237)
	at play.core.server.Server$.getHandlerFor(Server.scala:129)
	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:323)
	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:225)
	at akka.stream.impl.fusing.MapAsync$$anon$30.onPush(Ops.scala:1309)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:542)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:496)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:818)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

Calls to any endpoint return `[UnsatisfiedLinkError: edu.cmu.dynet.internal.dynet_swigJNI.new_DynetParams()J]`

**Comment by enoriega** [comment]
AFAIK there is a version of DyNet with a fat jar, probably this is easy to fix by updating the one included in the dependencies @kwalcock

**Comment by kwalcock** [comment]
It is trying to load the Linux .so file.  For Linux, the only compilation target is Intel.  The ARM version is for Mac OS.

**Comment by myedibleenso** [comment]
>For Linux, the only compilation target is Intel.

Ah, ok.  Thanks.  So this is something that there is no plan to address upstream?  Since processors is moving to an ONNX backbone, I guess it won't be an issue for very long.

**Comment by kwalcock** [comment]
I believe we are calling Rust tokenizers that are compiled in advance in the same way.  The plan has only been for the four targets Linux/Intel, Mac/Intel, Mac/ARM, Windows/Intel.  I suppose we can add another.

**Comment by myedibleenso** [comment]
+1 for linux/arm64

**Comment by enoriega** [comment]
+1

**Comment by kwalcock** [comment]
The next time I compile the Rust components, I'll check it out.  It would probably be some kind of cross-compilation rather than a native target.
