### ISSUE TITLE
[img2mml] Checkpoint trying to load to `cuda:1`

### ISSUE THREAD

**Issue by enoriega** [ml4ai/skema#468]
## Summary

When trying to load the pytorch model from `skema/img2mml/trained_models/cnn_xfmer_arxiv_im2mml_with_fonts_boldface_best.pt` in the presence of CUDA devices. It will arbitrarily try to load it to `device 1`.
If a computer only has one cuda device, the code won't load because there is `device 0` but not `device 1`.

Line the crashes:
https://github.com/ml4ai/skema/blob/6e848c8e986a318cd1b865b0116ec42fe8abf830/skema/img2mml/api.py#L111

## Proposed solution

Make it such that loading model in the presence of a cuda device, it always goes to the first one, unless otherwise specified via configuration.

## Stack Trace

```
Traceback (most recent call last):
  File "/media/evo870/github/skema2/skema/img2mml/api.py", line 111, in load_model
    model.load_state_dict(torch.load(model_path))
  File "/home/enrique/miniconda3/envs/skema-integration/lib/python3.8/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/enrique/miniconda3/envs/skema-integration/lib/python3.8/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/enrique/miniconda3/envs/skema-integration/lib/python3.8/site-packages/torch/serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/home/enrique/miniconda3/envs/skema-integration/lib/python3.8/site-packages/torch/serialization.py", line 1116, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/home/enrique/miniconda3/envs/skema-integration/lib/python3.8/site-packages/torch/serialization.py", line 217, in default_restore_location
    result = fn(storage, location)
  File "/home/enrique/miniconda3/envs/skema-integration/lib/python3.8/site-packages/torch/serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/enrique/miniconda3/envs/skema-integration/lib/python3.8/site-packages/torch/serialization.py", line 173, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on CUDA device '
RuntimeError: Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/enrique/miniconda3/envs/skema-integration/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/enrique/miniconda3/envs/skema-integration/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/enrique/miniconda3/envs/skema-integration/lib/python3.8/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/enrique/miniconda3/envs/skema-integration/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/enrique/miniconda3/envs/skema-integration/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/enrique/miniconda3/envs/skema-integration/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/enrique/miniconda3/envs/skema-integration/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/enrique/miniconda3/envs/skema-integration/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/enrique/miniconda3/envs/skema-integration/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/enrique/miniconda3/envs/skema-integration/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/media/evo870/github/skema2/skema/rest/api.py", line 4, in <module>
    from skema.rest import (
  File "/media/evo870/github/skema2/skema/rest/workflows.py", line 13, in <module>
    from skema.img2mml import eqn2mml
  File "/media/evo870/github/skema2/skema/img2mml/eqn2mml.py", line 36, in <module>
    image2mathml_db = Image2MathML(
  File "/media/evo870/github/skema2/skema/img2mml/api.py", line 161, in __init__
    self.model = self.load_model(model_path)
  File "/media/evo870/github/skema2/skema/img2mml/api.py", line 184, in load_model
    img2mml_model: Image2MathML_Xfmer = load_model(
  File "/media/evo870/github/skema2/skema/img2mml/api.py", line 115, in load_model
    raise RuntimeError(
RuntimeError: Error loading state dictionary from file: /media/evo870/github/skema2/skema/img2mml/trained_models/cnn_xfmer_arxiv_im2mml_with_fonts_boldface_best.pt
Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.

```

**Comment by ualiangzhang** [comment]
@enoriega Thanks for letting me know! The `image2mml` GPU call doesn't specify a particular GPU, as shown in the code below. I suspect there might be an issue with GPU visibility settings elsewhere.

https://github.com/ml4ai/skema/blob/6e848c8e986a318cd1b865b0116ec42fe8abf830/skema/img2mml/api.py#L173C5-L179C22

**Comment by enoriega** [comment]
The checkpoint will save the device in which it was trained. If you used leviathan/kraken to train it on gpu 1, it will try to load on gpu 1 anywhere else unless you specify explicitly another device.

**Comment by ualiangzhang** [comment]
@enoriega Thanks for the feedback!

Could you please change "cuda" to "cuda:0" in this line and test your code again? Thanks!

https://github.com/ml4ai/skema/blob/6e848c8e986a318cd1b865b0116ec42fe8abf830/skema/img2mml/api.py#L55


I added the following block to the `load_model` function and tested it on Leviathan which has 6 GPUs.
```
# Check if a GPU is available
if torch.cuda.is_available():
    # Get the current GPU device index
    current_gpu = torch.cuda.current_device()
    print(f"Currently using GPU {current_gpu}")
    # Get the GPU name
    gpu_name = torch.cuda.get_device_name(current_gpu)
    print(f"GPU Name: {gpu_name}")
else:
    print("No available GPU")
```
It printed
```
Currently using GPU 0
GPU Name: NVIDIA RTX A6000
```
I also tested this following command, which returned the same thing.
`CUDA_VISIBLE_DEVICES=0 uvicorn eqn2mml:app --reload`
